### PR TITLE
Removing Elixir With Love - website gone

### PR DESCRIPTION
**Pull request by spekulatius**

### CODE REVIEW

**Review by dreamingechoes — COMMENTED** [review]
Hi @spekulatius!

Thank you for this contribution! Before merging the pull request, don’t you want to add yourself to the contributor's list? Feel free to add yourself to the contributor's list (in alphabetical order by surname) in a new commit on this PR. Use the following format: `[Your Name](link)`.

Greetings! 🤗

**Comment by spekulatius** [comment]
Hey @dreamingechoes 

cheers for pointing this out. I've just added myself :+1: 

Peter

**Review by dreamingechoes — APPROVED** [review]
Awesome! I'll merge the PR right now! 🤗

**Comment by spekulatius** [comment]
Thank you @dreamingechoes :1st_place_medal:

**Pull request merged**
