### PR TITLE
Diverse figures in tech

### PR DESCRIPTION
**Pull request by alexcg1**
Adding an extensive section for diverse figures in tech history. Suggest we keep it in separate file for now since it's still very much a work in progress.

Any feedback would be very welcome!

### CODE REVIEW

**Comment by dreamingechoes** [comment]
Hi @alexcg1!

This is awesome! I love this contribution :smile: Let's keep this pull request open until we have a solid final version of the section. We can work all together to enrich as much as possible this, what do you think? @marinavega @tasugo 

Thank you very much for the hard work! :sparkling_heart:

**Comment by alexcg1** [comment]
I've added most of the interesting figures I can find, and populated as much as I can with photos, bios, and links. More or less finished v1.0 from my end

**Comment by dreamingechoes** [comment]
Awesome!

Before merging the pull request, don't you want to add yourself to the [contributor's list](https://github.com/folkswhocode/awesome-diversity/blob/master/CONTRIBUTORS.md)? :smile:

**Comment by alexcg1** [comment]
@dreamingechoes I'm already on there as Alex Cureton-Griffiths :)

**Comment by dreamingechoes** [comment]
Ouch! True, my apologies :bowing_man: :pray: 

I'll merge this right now! Again, thanks for your awesome work! :hugs: :sparkling_heart:

**Pull request merged**
