### PR TITLE
Add Dev Color org

### PR DESCRIPTION
**Pull request by Ch3ck**

### CODE REVIEW

**Comment by dreamingechoes** [comment]
Hi @Ch3ck!

Thank you for this awesome contribution! 😊💖 Before merging the pull request, don’t you want to add yourself to the contributors list?

Greetings! 🤗

**Comment by Ch3ck** [comment]
Sure @dreamingechoes I'll love to, is there a list?

**Comment by Ch3ck** [comment]
Done!

**Comment by dreamingechoes** [comment]
Awesome! I just saw your new pull request, I'll merge both right now! Again, thank you for your contribution 🤗💖

Greetings!

**Pull request merged**
